[package]
name = "roguelike_tut"
version = "0.1.0"
authors = ["ilya"]
edition = "2018"

[dependencies]
tcod = { version = "0.15", features = ["serialization"] }
rand = "0.3.9"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
